export const CUSTOMER_LIST = 'CUSTOMER_LIST';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const GET_NOTIFICATION_NO = 'GET_NOTIFICATION_NO';
export const GET_LOGS = 'GET_LOGS';
export const GET_LOG_BY_CUSTOMER = 'GET_LOG_BY_CUSTOMER';